### PR TITLE
Use distinct managed sources folders

### LINKED ISSUE #125: Intellij doesn't work with the plugin
Hello, thank you for the lib!

Using latest version of sbt-avo and avro-compile:
1. If I compile clean (no targets) project in Intellij it complains that Avro-generated classes are not found
2. If I first run `avroGenerate` then compile in Intellij - it complains that Avro-generated classes are defined 2 times

Any ideas how to solve that?
Thank you!

### PR DESCRIPTION
**Pull request by RustedBones**
Fix #125 

```diff
-target/scala-x.xx/src_managed/$config/avro/
+target/scala-x.xx/src_managed/avro/$config/

-target/scala-x.xx/src_managed/$config/compiled_avro/
+target/scala-x.xx/src_managed/compiled_avro/$config/
```

I'm not so sure on the schema libraries scoped in the test configuration. The compiler will regenerate java sources from the compile configuration, but I think there isn't a way around if the schema in test depend on a compile one.

### CODE REVIEW

File: src/main/scala/com/github/sbt/avro/SbtAvro.scala [hunk 1]
```diff
@@ -139,10 +142,12 @@ object SbtAvro extends AutoPlugin {
...
 
   private def unpackDependenciesTask(key: TaskKey[Seq[File]]) = Def.task {
+    val conf = configuration.value.toConfigRef
     val avroArtifacts = update
       .value
-      .filter((key / avroDependencyIncludeFilter).value)
-      .toSeq.map { case (_, _, _, file) => file }.distinct
+      .filter(avroDependencyIncludeFilter.value)
+      .toSeq
+      .collect { case (`conf`, _, _, file) => file }
```
Comment (RustedBones) [inline src/main/scala/com/github/sbt/avro/SbtAvro.scala:150]: This was a bug. configuration was not taken into account (a `Test` scoped lib would be compiled in `Compile`)
There should not be duplication when filtering on current configuration
